TRPO_GAE
Tom-Pecher/RL-CW pull request #28
Opened 2024-12-23 22:13 UTC by sef007

Added initial working implementation of TRPO.

2024-12-23 22:14 UTC, TheGogy commented
Closes #16 
Closes #15

2024-12-23 22:29 UTC, TheGogy commented
Might be an idea to create a separate directory in the repo that we can keep optimal agent weights so that we don't have to re-train.

2024-12-23 23:18 UTC, TheGogy requested changes
LGTM for the most part! A few minor changes but should be just about good to go.

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/policy_network.py
> +    def __init__(self, state_dim: int, action_dim: int, max_action: float, hidden_sizes: List[int]):
```suggestion
    def __init__(self, state_dim: int, action_dim: int, max_action: float, hidden_sizes: List[int], upper_bound: float, lower_bound: float):
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/policy_network.py
> +
```suggestion
    self.upper_bound = upper_bound
    self.lower_bound = lower_bound
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +        self.policy = PolicyNetwork(state_dim, action_dim, max_action, [64, 64]).to(device)
```suggestion
        UPPER_BOUND = 2
        LOWER_BOUND = -20
        self.policy = PolicyNetwork(state_dim, action_dim, max_action, [64, 64], UPPER_BOUND, LOWER_BOUND).to(device)
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +            while done == False:
```suggestion
            while not done:
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +                next_state, reward, terminated, truncated, dummy = env.step(action.cpu().numpy()[0])
```suggestion
                next_state, reward, terminated, truncated, _ = env.step(action.cpu().numpy()[0])
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +                    done = False
```suggestion
                # end the episode
                done = terminated or truncated
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +            t = t -1  # iterate backwards
```suggestion
            t -= 1 # Iterate backwards
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +            flat_grads_list.append(flat_grad)
```suggestion
        # get in one d vector 
        flat_grads_list = [g.view(-1) for g in grads]
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +            fisher_product_list.append(grad.contiguous().view(-1))
```suggestion
        # get in one d vector 
        fisher_product_list = [g.contiguous().view(-1) for g in grad_grads]
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/agent.py
> +            g.append(flat_grad)
```suggestion
        g = [grad.view(-1) for grad in grads]
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/policy_network.py
> +        clamped_log_std = self.log_std.clamp(min=lower_bound,max=upper_bound)  # range should allow decent convergence quickly
```suggestion
        # forward_mean = max_action * tanh(1/N sum of state policies)
        for_mean = self.max_action * torch.tanh(self.mean(self.policy(state)))  

        clamped_log_std = self.log_std.clamp(min=self.lower_bound,max=self.upper_bound)  # range should allow decent convergence quickly
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/record.py
Would be good to make a version of this for TRPO specifically. Would be happy to do this tonight

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/train.py
> +        episode_trigger=lambda ep: ep % 1000 == 0,
Might be an idea to record a few more videos

```suggestion
        episode_trigger=lambda ep: ep % 100 == 0,
```

2024-12-23 23:18 UTC, TheGogy commented on src/agents/trpo/train.py
> +    agent.policy.load_state_dict(torch.load("models/trpo/trpo_best_policy.pth"))
Might be an idea to leave this for the recording? The train should train an agent from scratch.

2024-12-24 22:34 UTC, Tom-Pecher reviewed
I agree with these changes. Let's get them implemented as soon as possible.

2024-12-31 13:28 UTC, merged